// Assemble the machine-readable decision brief: a single normalized object that
// the UI and an LLM both consume, plus a compact Markdown rendering for direct
// prompting. Bull/bear points and risk flags are derived from the data — numbers
// are never invented, and missing inputs stay null.
import { isNum } from './quantutil.js';

const SCHEMA_VERSION = '1.0';
const DISCLAIMER =
  'Generated by an automated model from third-party data for research and educational use. ' +
  'Not investment advice. Verify independently before acting.';

const pct = (x, dp = 1) => (isNum(x) ? (x * 100).toFixed(dp) + '%' : '—');
const num = (x, dp = 2) => (isNum(x) ? Number(x).toFixed(dp) : '—');
const money = (x) => (isNum(x) ? '$' + Number(x).toFixed(2) : '—');

function deriveFlags(ex, val) {
  const f = [];
  if (isNum(ex.fcf) && ex.fcf < 0) f.push('Negative free cash flow');
  if (isNum(ex.debtToEquity) && ex.debtToEquity > 200) f.push(`High leverage (D/E ${num(ex.debtToEquity, 0)}%)`);
  if (isNum(ex.netDebtToEbitda) && ex.netDebtToEbitda > 4) f.push(`Net debt ${num(ex.netDebtToEbitda, 1)}x EBITDA`);
  if (isNum(ex.interestCoverage) && ex.interestCoverage < 2) f.push('Thin interest coverage (<2x)');
  if (isNum(ex.earningsGrowth) && ex.earningsGrowth < 0) f.push('Declining earnings (YoY)');
  if (isNum(ex.revenueGrowth) && ex.revenueGrowth < 0) f.push('Declining revenue (YoY)');
  if (isNum(ex.earningsYield) && ex.earningsYield > 0 && ex.earningsYield < 0.03)
    f.push('Richly valued (earnings yield <3%)');
  if (ex.signals?.trend === 'down') f.push('Below 200-day moving average (downtrend)');
  if (isNum(ex.marginVsHist) && ex.marginVsHist > 1.3)
    f.push(`Net margin ${num(ex.marginVsHist, 1)}× its multi-year average — possible peak earnings (cyclical risk)`);
  if (isNum(val?.valueCreationSpread) && val.valueCreationSpread < 0)
    f.push(`Returns below cost of capital (ROIC ${pct(val.roic)} < WACC ${pct(val.wacc)})`);
  if (isNum(ex.cashConversion) && ex.cashConversion < 0.6)
    f.push(`Weak cash conversion (CFO ${num(ex.cashConversion, 2)}× net income) — earnings not backed by cash`);
  // Compare the price-implied growth to OUR assumed stage-1 growth (same basis),
  // not to historical EPS CAGR, and use an absolute gap so the flag is meaningful.
  if (isNum(val?.impliedGrowth) && isNum(val?.assumptions?.stage1Growth) && val.impliedGrowth - val.assumptions.stage1Growth > 0.05)
    f.push('Price implies growth >5pp above our estimate');
  return f;
}

function deriveBull(ex, factors, val) {
  const b = [];
  if (factors.quality.score >= 70)
    b.push(`High business quality — ROE ${pct(ex.roe)}, net margin ${pct(ex.netMargin)}.`);
  if (isNum(val?.valueCreationSpread) && val.valueCreationSpread > 0.02)
    b.push(`Creates value — ROIC ${pct(val.roic)} above WACC ${pct(val.wacc)} (${pct(val.valueCreationSpread)} spread).`);
  if (factors.value.score >= 65)
    b.push(`Reasonable valuation — earnings yield ${pct(ex.earningsYield)}, FCF yield ${pct(ex.fcfYield)}.`);
  if (factors.growth.score >= 65)
    b.push(`Durable growth — revenue CAGR ${pct(ex.revCagr3)}, EPS CAGR ${pct(ex.epsCagr3)}.`);
  if (isNum(val?.marginOfSafety) && val.marginOfSafety > 0.15)
    b.push(`Trades ${pct(val.marginOfSafety)} below blended fair value (margin of safety).`);
  if (factors.momentum.score >= 65 && ex.signals?.trend === 'up')
    b.push(`Positive long-term trend — above 200d MA, 12–1 momentum ${pct(ex.signals?.mom12_1)}.`);
  if (isNum(ex.shareholderYield) && ex.shareholderYield > 0.04)
    b.push(`Returning capital — shareholder yield ${pct(ex.shareholderYield)}.`);
  if (isNum(ex.analystUpside) && ex.analystUpside > 0.1)
    b.push(`Analysts see ${pct(ex.analystUpside)} upside to mean target (${ex.analystCount ?? '—'} analysts).`);
  return b;
}

function deriveBear(ex, factors, val) {
  const b = [];
  if (factors.value.score < 35)
    b.push(`Expensive — earnings yield ${pct(ex.earningsYield)}, EV/EBITDA ${num(ex.evEbitda, 1)}.`);
  if (factors.health.score < 40)
    b.push(`Balance-sheet risk — D/E ${num(ex.debtToEquity, 0)}%, current ratio ${num(ex.currentRatio, 2)}.`);
  if (factors.growth.score < 35)
    b.push(`Weak growth — revenue YoY ${pct(ex.revenueGrowth)}, earnings YoY ${pct(ex.earningsGrowth)}.`);
  if (factors.momentum.score < 35)
    b.push(`Weak trend — ${pct(ex.signals?.priceVsSma200)} vs 200d MA, 6m return ${pct(ex.signals?.ret6m)}.`);
  if (isNum(val?.marginOfSafety) && val.marginOfSafety < -0.15)
    b.push(`Trades ${pct(-val.marginOfSafety)} above blended fair value.`);
  if (isNum(ex.signals?.maxDrawdown) && ex.signals.maxDrawdown < -0.4)
    b.push(`Historically volatile — max drawdown ${pct(ex.signals.maxDrawdown)}.`);
  return b;
}

export function buildBrief({ ex, factors, weights, comp, valuation, dataQuality, reliability = 'standard', actionable = true, modelNotes = [], news = [], holdingPeriod = null, benchmark = null, warnings = [] }) {
  const flags = deriveFlags(ex, valuation);
  const bull = deriveBull(ex, factors, valuation);
  const bear = deriveBear(ex, factors, valuation);

  return {
    schemaVersion: SCHEMA_VERSION,
    symbol: ex.symbol,
    name: ex.name,
    asOf: new Date().toISOString(),
    price: ex.price,
    currency: ex.currency,
    sector: ex.sector,
    industry: ex.industry,
    sectorClass: ex.sectorClass,
    reliability,
    modelNotes,
    scorecard: {
      composite: round(comp.composite),
      rating: comp.rating,
      actionable,
      conviction: round(comp.conviction, 2),
      coverage: round(comp.coverage, 2),
      weights,
      factors: Object.fromEntries(
        Object.entries(factors).map(([k, f]) => [
          k,
          { score: round(f.score), coverage: round(f.coverage, 2), inputs: f.inputs },
        ])
      ),
    },
    valuation,
    signals: ex.signals,
    holdingPeriod, // forward 1/2/3y total-return distribution (look-ahead-free, gated by effectiveN)
    benchmark, // trailing return vs SPY/QQQ — opportunity cost of a single name
    warnings, // typed honesty flags (absolute anchors, survivorship/regime)
    fundamentals: {
      marketCap: ex.marketCap,
      pe: ex.pe,
      forwardPe: ex.forwardPe,
      evEbitda: ex.evEbitda,
      roe: ex.roe,
      roic: ex.roic,
      netMargin: ex.netMargin,
      cashConversion: ex.cashConversion,
      fcf: ex.fcf,
      revenueGrowth: ex.revenueGrowth,
      earningsGrowth: ex.earningsGrowth,
      debtToEquity: ex.debtToEquity,
      dividendYield: ex.dividendYield,
      shareholderYield: ex.shareholderYield,
      beta: ex.beta,
      analystRec: ex.analystRec,
      targetMean: ex.targetMean,
      analystUpside: ex.analystUpside,
    },
    flags,
    bull,
    bear,
    news,
    dataQuality,
    disclaimer: DISCLAIMER,
  };
}

function round(x, dp = 1) {
  return isNum(x) ? +x.toFixed(dp) : null;
}

// Compact Markdown rendering — designed to be pasted straight into an LLM prompt.
export function briefToMarkdown(b) {
  const f = b.scorecard.factors;
  const fc = (k, label) => `| ${label} | ${num0(f[k]?.score)} | ${pct(f[k]?.coverage, 0)} |`;
  const v = b.valuation || {};
  const lines = [
    `# ${b.symbol} — ${b.name || ''}`,
    `*As of ${b.asOf.slice(0, 10)} · ${b.sector || ''} / ${b.industry || ''}*`,
    ``,
    `**Decision score: ${num0(b.scorecard.composite)}/100 → ${b.scorecard.actionable ? b.scorecard.rating : b.scorecard.rating + ' (screen only — not actionable)'}**  `,
    `Conviction ${num(b.scorecard.conviction, 2)} · data coverage ${pct(b.scorecard.coverage, 0)} · model reliability: ${b.reliability}`,
    ...(b.modelNotes && b.modelNotes.length ? ['', ...b.modelNotes.map((n) => `> ⚠ ${n}`)] : []),
    ``,
    `## Factor scores`,
    `| Factor | Score | Coverage |`,
    `| --- | --- | --- |`,
    fc('quality', 'Quality'),
    fc('value', 'Value'),
    fc('growth', 'Growth'),
    fc('health', 'Health'),
    fc('momentum', 'Momentum'),
    fc('shareholderYield', 'Shareholder yield'),
    ``,
    `## Valuation`,
    `- Price: ${money(b.price)}`,
    `- DCF fair value: ${money(v.dcfValue)} · Multiples: ${money(v.multiplesValue)} · Blended: ${money(v.blendedFairValue)}`,
    `- Margin of safety: ${pct(v.marginOfSafety)}`,
    `- Market-implied growth (reverse DCF): ${pct(v.impliedGrowth)} vs assumed ${pct(v.assumptions?.stage1Growth)}`,
    `- ROIC ${pct(v.roic)} vs WACC ${pct(v.wacc)} → value-creation spread ${pct(v.valueCreationSpread)}`,
    `- Analyst mean-target upside: ${pct(v.analystUpside)}`,
    ``,
    `## Signals`,
    `- Trend: ${b.signals?.trend || '—'} (price vs 200d MA ${pct(b.signals?.priceVsSma200)})`,
    `- 12–1 momentum: ${pct(b.signals?.mom12_1)} · 6m: ${pct(b.signals?.ret6m)} · 12m: ${pct(b.signals?.ret12m)}`,
    `- Annualized vol: ${pct(b.signals?.annualVol)} · max drawdown: ${pct(b.signals?.maxDrawdown)}`,
    ``,
    ...benchmarkLines(b.benchmark),
    ...holdingPeriodLines(b.holdingPeriod),
    `## Bull case`,
    ...(b.bull.length ? b.bull.map((x) => `- ${x}`) : ['- (none triggered)']),
    ``,
    `## Bear case`,
    ...(b.bear.length ? b.bear.map((x) => `- ${x}`) : ['- (none triggered)']),
    ``,
    `## Risk flags`,
    ...(b.flags.length ? b.flags.map((x) => `- ⚠ ${x}`) : ['- none']),
    ``,
    ...(b.warnings && b.warnings.length ? ['## Interpretation warnings', ...b.warnings.map((w) => `- ⚠ ${w.message}`), ``] : []),
    `## Recent headlines`,
    ...(b.news && b.news.length ? b.news.map((n) => `- ${n.title}${n.publisher ? ` — ${n.publisher}` : ''}${n.published ? ` (${n.published})` : ''}`) : ['- (none)']),
    ``,
    `---`,
    `_${b.disclaimer}_`,
  ];
  return lines.join('\n');
}

const num0 = (x) => (isNum(x) ? Math.round(x) : '—');

// Benchmark (opportunity-cost) block: stock trailing CAGR vs the index it competes with.
function benchmarkLines(bm) {
  if (!bm || !bm.stock) return [];
  const row = (label, t) => `- ${label}: 1y ${pct(t.cagr1y)} · 3y ${pct(t.cagr3y)} · 5y ${pct(t.cagr5y)} · vol ${pct(t.vol)} · maxDD ${pct(t.maxDrawdown)}`;
  const lines = [`## Vs benchmark (opportunity cost)`, row('This stock', bm.stock)];
  for (const [label, t] of Object.entries(bm.indices)) lines.push(row(label, t));
  const ex = Object.entries(bm.excess).map(([k, e]) => `${k} ${pct(e.cagr3y)}`).join(' · ');
  if (ex) lines.push(`- Excess 3y CAGR vs ${ex} (not risk-adjusted)`);
  lines.push(``);
  return lines;
}

// Forward holding-period distribution: what holding 1/2/3y has historically delivered.
function holdingPeriodLines(hp) {
  if (!hp) return [];
  const lines = [`## Forward holding-period return (historical, descriptive)`];
  for (const k of ['y1', 'y2', 'y3']) {
    const h = hp[k];
    if (!h || !h.all) continue;
    const lc = h.lowConfidence ? ` ⚠ low confidence (${h.effectiveN} independent windows)` : '';
    lines.push(`- ${k.slice(1)}y: median ${pct(h.all.median)} · p25 ${pct(h.all.p25)} · p75 ${pct(h.all.p75)} · %positive ${pct(h.all.pctPositive, 0)}${lc}`);
  }
  lines.push(`_Overlapping windows in a single regime — descriptive base rates, not a forecast._`, ``);
  return lines;
}
